//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoTAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdPartyUserIdentity
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Token { get; set; }
        public string RefreshToken { get; set; }
        public System.DateTime TokenExpirationDate { get; set; }
        public Nullable<System.DateTime> LastSync { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ThirdPartyServices ThirdPartyServices { get; set; }
    }
}
